FROM node:10.7
RUN mkdir /app
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY . /app/
ARG SOCKET_URL=http://localhost:8000
RUN /app/node_modules/.bin/webpack -p --env.SOCKET_URL=$SOCKET_URL

FROM nginx:1.15
COPY --from=0 /app/dist/* /usr/share/nginx/html/
